version: '3.3'

services:
  mysql:
    image: 'mysql/mysql-server:8.0.27'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=accounts
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev123456

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - '6379'
